GimmeBook\Infrastructure\Entity\Book\Author:
  type: entity
  repositoryClass: GimmeBook\Infrastructure\Repository\Book\AuthorRepositoryInterface
  table: author
  indexes:
    name__idx:
      columns: [ name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 100
      column: name
  manyToMany:
    books:
      targetEntity: GimmeBook\Infrastructure\Entity\Book\Book
      mappedBy: authors
